name: b2b_marketplace
description: "B2B Fashion Manufacturing Marketplace for Egypt"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^15.1.2

  # Dependency Injection
  get_it: ^8.0.3

  # Localization
  easy_localization: ^3.0.7+1

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # UI Utilities
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.0+3

  # Functional Error Handling
  dartz: ^0.10.1

  # Backend
  supabase_flutter: ^2.9.0

  # Media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Utils
  uuid: ^4.5.1
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  qr_flutter: ^4.1.0
  data_table_2: ^2.7.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
