import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

/// Generates professional PDF documents for RFQs and Quotes.
class PdfService {
  /// Generate a PDF for an RFQ request.
  Future<Uint8List> generateRfqPdf({
    required String rfqTitle,
    required String rfqDescription,
    required int quantity,
    required String brandName,
    required String brandEmail,
    required String? factoryName,
    required DateTime createdAt,
    required String rfqId,
  }) async {
    final pdf = pw.Document(theme: pw.ThemeData.withFont());

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              _buildHeader('REQUEST FOR QUOTATION'),
              pw.SizedBox(height: 20),

              // RFQ Info Row
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      _labelValue(
                        'RFQ ID',
                        rfqId.substring(0, 8).toUpperCase(),
                      ),
                      pw.SizedBox(height: 4),
                      _labelValue('Date', DateFormat.yMMMd().format(createdAt)),
                    ],
                  ),
                  pw.BarcodeWidget(
                    barcode: pw.Barcode.qrCode(),
                    data: 'b2b-marketplace://rfq/$rfqId',
                    width: 70,
                    height: 70,
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 16),

              // Brand Details
              _sectionTitle('FROM (Brand)'),
              pw.SizedBox(height: 8),
              _labelValue('Company', brandName),
              _labelValue('Email', brandEmail),
              pw.SizedBox(height: 16),

              // Factory Details (if assigned)
              if (factoryName != null) ...[
                _sectionTitle('TO (Factory)'),
                pw.SizedBox(height: 8),
                _labelValue('Factory', factoryName),
                pw.SizedBox(height: 16),
              ],

              // RFQ Content
              _sectionTitle('RFQ DETAILS'),
              pw.SizedBox(height: 8),
              _labelValue('Title', rfqTitle),
              pw.SizedBox(height: 4),
              _labelValue('Quantity', '$quantity units'),
              pw.SizedBox(height: 8),
              pw.Text(
                'Description:',
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 11,
                ),
              ),
              pw.SizedBox(height: 4),
              pw.Container(
                padding: const pw.EdgeInsets.all(12),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.grey300),
                  borderRadius: pw.BorderRadius.circular(4),
                ),
                child: pw.Text(
                  rfqDescription,
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ),

              pw.Spacer(),

              // Signature space
              pw.Divider(),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _signatureBlock('Brand Signature'),
                  _signatureBlock('Date'),
                ],
              ),

              pw.SizedBox(height: 16),
              pw.Center(
                child: pw.Text(
                  'Generated by B2B Marketplace',
                  style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  /// Generate a PDF for a Quote response.
  Future<Uint8List> generateQuotePdf({
    required String quoteId,
    required String rfqTitle,
    required int quantity,
    required double price,
    required int leadTime,
    required String? notes,
    required String factoryName,
    required String brandName,
    required DateTime createdAt,
    required String rfqId,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildHeader('QUOTATION'),
              pw.SizedBox(height: 20),

              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      _labelValue(
                        'Quote ID',
                        quoteId.substring(0, 8).toUpperCase(),
                      ),
                      pw.SizedBox(height: 4),
                      _labelValue('Date', DateFormat.yMMMd().format(createdAt)),
                      pw.SizedBox(height: 4),
                      _labelValue(
                        'RFQ Ref',
                        rfqId.substring(0, 8).toUpperCase(),
                      ),
                    ],
                  ),
                  pw.BarcodeWidget(
                    barcode: pw.Barcode.qrCode(),
                    data: 'b2b-marketplace://quote/$quoteId',
                    width: 70,
                    height: 70,
                  ),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 16),

              // Parties
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        _sectionTitle('FROM (Factory)'),
                        pw.SizedBox(height: 8),
                        _labelValue('Factory', factoryName),
                      ],
                    ),
                  ),
                  pw.Expanded(
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        _sectionTitle('TO (Brand)'),
                        pw.SizedBox(height: 8),
                        _labelValue('Company', brandName),
                      ],
                    ),
                  ),
                ],
              ),
              pw.SizedBox(height: 20),

              // Quote details table
              _sectionTitle('QUOTE DETAILS'),
              pw.SizedBox(height: 8),
              pw.TableHelper.fromTextArray(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 10,
                ),
                cellStyle: const pw.TextStyle(fontSize: 10),
                headerDecoration: const pw.BoxDecoration(
                  color: PdfColors.grey100,
                ),
                cellPadding: const pw.EdgeInsets.all(8),
                headers: [
                  'Item',
                  'Quantity',
                  'Unit Price',
                  'Lead Time',
                  'Total',
                ],
                data: [
                  [
                    rfqTitle,
                    '$quantity units',
                    '\$${price.toStringAsFixed(2)}',
                    '$leadTime days',
                    '\$${(price * quantity).toStringAsFixed(2)}',
                  ],
                ],
              ),

              if (notes != null && notes.isNotEmpty) ...[
                pw.SizedBox(height: 16),
                _sectionTitle('NOTES'),
                pw.SizedBox(height: 8),
                pw.Container(
                  padding: const pw.EdgeInsets.all(12),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: pw.BorderRadius.circular(4),
                  ),
                  child: pw.Text(
                    notes,
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                ),
              ],

              pw.Spacer(),

              // Signatures
              pw.Divider(),
              pw.SizedBox(height: 20),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  _signatureBlock('Factory Signature'),
                  _signatureBlock('Brand Signature'),
                ],
              ),

              pw.SizedBox(height: 16),
              pw.Center(
                child: pw.Text(
                  'Generated by B2B Marketplace',
                  style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }

  // ── Private helpers ──

  pw.Widget _buildHeader(String title) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(vertical: 16, horizontal: 20),
      decoration: const pw.BoxDecoration(
        color: PdfColors.blue800,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 22,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.white,
        ),
      ),
    );
  }

  pw.Widget _sectionTitle(String text) {
    return pw.Text(
      text,
      style: pw.TextStyle(
        fontSize: 13,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.blue800,
      ),
    );
  }

  pw.Widget _labelValue(String label, String value) {
    return pw.RichText(
      text: pw.TextSpan(
        children: [
          pw.TextSpan(
            text: '$label: ',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
          ),
          pw.TextSpan(text: value, style: const pw.TextStyle(fontSize: 10)),
        ],
      ),
    );
  }

  pw.Widget _signatureBlock(String label) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Container(width: 180, height: 1, color: PdfColors.grey400),
        pw.SizedBox(height: 4),
        pw.Text(
          label,
          style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
        ),
      ],
    );
  }
}
