// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqb4UHvlhzzGHoVJsjBY3OjT-f0TNbQ6c',
    appId: '1:671945146757:web:a035779a3b5e9f2c9304ec',
    messagingSenderId: '671945146757',
    projectId: 'b2b-marketplace-55b4a',
    authDomain: 'b2b-marketplace-55b4a.firebaseapp.com',
    storageBucket: 'b2b-marketplace-55b4a.firebasestorage.app',
    measurementId: 'G-XP87PGJJET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf1D6sl-XzCCyhn3Jg6qCRaL_tTev_Xw8',
    appId: '1:671945146757:android:adb41eaebc3d34339304ec',
    messagingSenderId: '671945146757',
    projectId: 'b2b-marketplace-55b4a',
    storageBucket: 'b2b-marketplace-55b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nRsRBlkkh2yy2yhdvIkeO7TuEyBaOhc',
    appId: '1:671945146757:ios:57e45813b1a20efc9304ec',
    messagingSenderId: '671945146757',
    projectId: 'b2b-marketplace-55b4a',
    storageBucket: 'b2b-marketplace-55b4a.firebasestorage.app',
    iosBundleId: 'com.example.b2bMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nRsRBlkkh2yy2yhdvIkeO7TuEyBaOhc',
    appId: '1:671945146757:ios:57e45813b1a20efc9304ec',
    messagingSenderId: '671945146757',
    projectId: 'b2b-marketplace-55b4a',
    storageBucket: 'b2b-marketplace-55b4a.firebasestorage.app',
    iosBundleId: 'com.example.b2bMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqb4UHvlhzzGHoVJsjBY3OjT-f0TNbQ6c',
    appId: '1:671945146757:web:0c4770f2211498e19304ec',
    messagingSenderId: '671945146757',
    projectId: 'b2b-marketplace-55b4a',
    authDomain: 'b2b-marketplace-55b4a.firebaseapp.com',
    storageBucket: 'b2b-marketplace-55b4a.firebasestorage.app',
    measurementId: 'G-LMEEKDXNL1',
  );
}
